name: "Feature request"
description: Suggest an idea
labels: ["type:feature","status:triage"]
body:
  - type: textarea
    id: problem
    attributes: { label: Problem to solve, description: What user need does this address? }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Proposed solution, description: Describe UI/UX/API changes }
  - type: textarea
    id: alternatives
    attributes: { label: Alternatives considered }
